### ISSUE TITLE
db.py的sqlite不是多线程的

### ISSUE THREAD

**Issue by whiteclover** [makto/FileHub#2]
db.py的SQLite封装不是多线程的， 在多线程中会出现 “Database LOCKED Error”， 在Tornado虽是异步，但也非常慢， 因所以把相关的 连接放于 线程独享区，比较好。 相关操作，希望连接操作改进和加入

**Comment by makto** [comment]
Thank you !

plus，你是如何启用tornado的多线程的？

plus2，pull request木有测试哇，有些小错
